### ISSUE TITLE
Move celo CLI documentation to celo module

### ISSUE THREAD

**Issue by mpetrun5** [ChainSafe/chainbridge-core#188]
Currently, it is confusing a bit as we have both evm-cli and celo-cli documentation 
inside chainbridge-core even though celo is not supported by chainbridge-core
and there can also be inconsistencies if celo-module currently supports
old version of chainbridge-core.

Also, fix README under `Modules` to say `chainbridge-core` only supports two modules:
 - EVM
 - Substrate

## Implementation details

Move celo cli documentation to chainbridge-celo-module.

**Comment by waymobetta** [comment]
Yes, I see the confusion and this is something @P1sar and I have discussed a bit previously. We were thinking it would be good to store all CLI commands within core README rather than within their respective project repos (like celo-module, substrate-module, etc) for easier management...but also, you bring up a good point about how core is not immediately compatible with these other modules, and so therefore running locally via example/app.go would not work without modification.

I think this is definitely an important topic of conversation that we need to discuss and make sure we're all on the same page. Maybe we talk about it but not in discussions page, rather as a team during our weekly call?

**Comment by mpetrun5** [comment]
> Yes, I see the confusion and this is something @P1sar and I have discussed a bit previously. We were thinking it would be good to store all CLI commands within core README rather than within their respective project repos (like celo-module, substrate-module, etc) for easier management...but also, you bring up a good point about how core is not immediately compatible with these other modules, and so therefore running locally via example/app.go would not work without modification.
> 
> I think this is definitely an important topic of conversation that we need to discuss and make sure we're all on the same page. Maybe we talk about it but not in discussions page, rather as a team during our weekly call?

:+1:
